### ISSUE TITLE
Add customisation for bash process

### ISSUE THREAD

**Issue by jgrzebyta** [jaredcdavis/shellpool#12]
It would be useful if an environmental variable might be customised by user during the bash start.
E.g.

```
(shellpool:start 7 :setenv '("FILENAME=/tmp/some-file.bat"))
```

In that way it would be possible to pass some pre-computing results into the pipeline.

**Comment by jaredcdavis** [comment]
I think this makes me a little nervous, because for instance if I run:

```
(shellpool:start 3 :setenv '("FOO=1"))
(shellpool:start 3 :setenv '("FOO=2"))
```

Then when I run `(shellpool:run "echo $FOO")` it will end up printing either 1 or 2 depending on which shell it happens to get run in.  Maybe this isn't a huge deal since it's likely that you'll start all your shells at once at the start of your program.

Do you have a case where just setting the variables at the start of your `shellpool:run` command doesn't work well for some reason?

**Comment by jgrzebyta** [comment]
You are right. I found another solution: I will directly call `shellpool:run "export FOO=1; ...[rest]"`.

**Comment by jaredcdavis** [comment]
Sounds great -- I think that's likely to work out much better.  I'll go ahead and close this.

Cheers,
Jared
